# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"